/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;


class AppTest {

  @Test
  void testAppHasAGreeting() {
    App classUnderTest = new App();
    assertThat(classUnderTest.getGreeting()).as("app should have a greeting")
      .isNotNull();

  }
}
